# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [33]:
import numpy as np


#### 3. Create a null vector of size 10 (★☆☆)

In [7]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [9]:
a = np.arange(10, 50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [10]:
a = np.arange(10, 50)
b = a[::-1]
print(a)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [11]:
a = np.arange(0, 9).reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
a = np.array([1, 2, 0, 0, 4, 0])
b = np.nonzero(a)
c = b[0]
print(c)

[0 1 4]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [3]:
a = np.random.rand(3,3,3)
print(a)

[[[0.95433592 0.59449357 0.21900867]
  [0.67193272 0.6098792  0.11070529]
  [0.54221216 0.91501514 0.65157483]]

 [[0.27782819 0.12583204 0.44557885]
  [0.68387565 0.96159102 0.16765763]
  [0.43199159 0.29670826 0.62055356]]

 [[0.10429964 0.74275779 0.32452941]
  [0.59422113 0.72687867 0.82304463]
  [0.48102592 0.47683182 0.15727712]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [4]:
a = np.random.rand(10,10)
b = np.min(a)
c = np.max(a)
print(a)
print(b)
print(c)

[[0.14018508 0.48038029 0.65807344 0.14393907 0.37932268 0.26308161
  0.81807064 0.45773323 0.33753775 0.22462872]
 [0.95333033 0.68123529 0.37881499 0.91111217 0.00829859 0.45229762
  0.81718691 0.73207707 0.05076977 0.9670802 ]
 [0.1628234  0.74549857 0.39828486 0.92862671 0.44742489 0.55709216
  0.30857493 0.57143608 0.7886797  0.17704861]
 [0.22471926 0.88279601 0.37936839 0.04796336 0.96577684 0.36462282
  0.9296562  0.27315471 0.50775708 0.94767525]
 [0.66372035 0.98656381 0.43412877 0.19503962 0.21493825 0.83377279
  0.75980141 0.40296518 0.27605751 0.51177521]
 [0.55960889 0.69008189 0.47373984 0.8276678  0.62553279 0.05120701
  0.72248942 0.87149689 0.31292116 0.99118517]
 [0.49712828 0.84975895 0.56522804 0.92753845 0.08172633 0.59377285
  0.47979865 0.47622724 0.63153156 0.72288322]
 [0.34221442 0.96638924 0.370178   0.21816293 0.18508271 0.03667236
  0.03036275 0.70667295 0.10264178 0.15276905]
 [0.60784796 0.55390164 0.9076014  0.35438358 0.30399892 0.92007429
  0.25404183

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [6]:
a = np.random.rand(30)
b = np.mean(a)
print(a)
print(b)

[0.38564435 0.77647398 0.30042688 0.50067166 0.19160037 0.02244591
 0.67732543 0.70365074 0.34874548 0.12543289 0.48975442 0.99656121
 0.03060847 0.80309173 0.70100926 0.5465108  0.64479872 0.75131755
 0.80529918 0.12793777 0.97471612 0.63999103 0.47904382 0.70972082
 0.19566353 0.29370895 0.47315976 0.84985599 0.57888722 0.10572386]
0.50765926410179


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [8]:
a = np.ones((5, 5))
print(a)
a[1:4, 1:4] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

Use np.pad().
For example, let A be an array.
B = np.pad(A, pad_width = 1, mode = 'constant', constant = 0)

In [10]:
A = np.random.rand(3,3,3)
B = np.pad(A, pad_width = 1, mode = 'constant', constant_values = 0)
print(B)

[[[0.         0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.        ]
  [0.         0.         0.         0.         0.        ]]

 [[0.         0.         0.         0.         0.        ]
  [0.         0.12697469 0.95429689 0.9583837  0.        ]
  [0.         0.6098923  0.81773301 0.3581532  0.        ]
  [0.         0.76601658 0.10940276 0.6372721  0.        ]
  [0.         0.         0.         0.         0.        ]]

 [[0.         0.         0.         0.         0.        ]
  [0.         0.16298364 0.00575323 0.40246523 0.        ]
  [0.         0.52929397 0.98978169 0.84935433 0.        ]
  [0.         0.14134602 0.02684604 0.8387519  0.        ]
  [0.         0.         0.         0.         0.        ]]

 [[0.         0.         0.         0.         0.        ]
  [0.         0.80269842 0.56965187 0.37163166 0. 

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [17]:
a = np.arange(1, 5)
b = np.diag(a, k = -1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [18]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [19]:
A = np.random.rand(5, 5)
b = np.linalg.norm(A)
B = A / b
print(A)
print(B)


[[0.08936676 0.04388954 0.20738704 0.00856145 0.52164842]
 [0.99095646 0.13365697 0.29814581 0.01557276 0.7213379 ]
 [0.88809895 0.35904986 0.71839941 0.41898556 0.87614784]
 [0.64143091 0.48531934 0.3437058  0.48586821 0.99202774]
 [0.85698059 0.9036735  0.28520519 0.80276441 0.5252138 ]]
[[0.03004149 0.01475389 0.06971513 0.00287801 0.17535709]
 [0.33311947 0.04493006 0.10022456 0.00523493 0.24248462]
 [0.29854293 0.12069804 0.24149681 0.14084599 0.29452545]
 [0.21562312 0.16314473 0.11553998 0.16332923 0.33347959]
 [0.2880822  0.30377847 0.09587445 0.26985691 0.17655563]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

Let a be the array.
Then a[3 : 9] = -a[3 : 9].


In [20]:
a = np.arange(0,11)
print(a)
a[3 : 9] = -a[3 : 9]
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 29. How to round away from zero a float array ? (★☆☆)

Let A be an array.
Then use np.sign(A) * np.ceil(np.abs(A)).

In [12]:
A = np.random.randn(1,10)
B = np.sign(A) * np.ceil(np.abs(A))
print(A)
print(B)

[[-0.43655147  0.40083611 -1.37229607 -0.97304626 -0.97877161 -0.52221554
   1.48246094  0.1919241  -0.02867676 -1.39831945]]
[[-1.  1. -2. -1. -1. -1.  2.  1. -1. -2.]]


#### 30. How to find common values between two arrays? (★☆☆)

Use np.intersect1d().
For example, let A and B be arrays.
C = np.intersect1d(A, B)


In [3]:
A = np.arange(0, 10)
B = np.identity(2)
C = np.intersect1d(A, B)
print(A)
print(B)
print(C)

[0 1 2 3 4 5 6 7 8 9]
[[1. 0.]
 [0. 1.]]
[0. 1.]


#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [4]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-4-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [5]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [10]:
a = np.linspace(0, 1, num = 11, endpoint = False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
a = np.random.randn(1, 10)
b = np.sort(a)
print(a)
print(b)

[[ 1.39145405 -0.57543539 -1.31483941  0.77680236 -1.29850326 -0.57516068
  -0.55396092  0.01303196 -0.72588742 -1.98111977]]
[[-1.98111977 -1.31483941 -1.29850326 -0.72588742 -0.57543539 -0.57516068
  -0.55396092  0.01303196  0.77680236  1.39145405]]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

Use np.array_equal(A, B).

In [13]:
A = np.random.randn(2,2)
B = np.random.randn(2,2)
print(A)
print(B)
print(np.array_equal(A, B))

[[ 0.56755378  0.62242602]
 [-0.0663011  -0.59997846]]
[[-0.82552635 -0.30422001]
 [-0.51901714 -0.67895227]]
False


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [15]:
a = np.random.rand(10)
print(a)

a[a.argmax()] = 0
print(a)

[0.05177529 0.34504776 0.34243882 0.89762231 0.00604702 0.30848095
 0.7307775  0.82893015 0.97351575 0.48841932]
[0.05177529 0.34504776 0.34243882 0.89762231 0.00604702 0.30848095
 0.7307775  0.82893015 0.         0.48841932]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

Let a be a vector and c be a scalar.
b = np.abs(a-c)
index_closest = b.argmin()
closest = a[index_closest]

In [29]:
a = np.random.randn(10)
c = 2.5
b = np.abs(a-c)
index_closest = b.argmin()
closest = a[index_closest]
print(a)
print(c)
print(closest)

[-1.82393828 -0.59996833 -0.73438083  1.1196138  -0.51355302 -1.11693873
  1.62762274  1.73447041 -0.67404465  0.25252296]
2.5
1.7344704052683466


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

Let A be the array.
Then use a = a.astype('int32').

In [31]:
a = np.array([1.5, 2.5], dtype='float32')
print(a)
a = a.astype('int32')
print(a)

[1.5 2.5]
[1 2]


#### 59. How to sort an array by the nth column? (★★☆)

Let A be a 2D array.
b = A[:,n-1] which is the n-th column.
c = b.argsort()
d = a[c]


In [37]:
A = np.random.rand(3,4)
b = A[:, 3]
c = b.argsort()
d = A[c]
print(A)
print(d)

[[0.07702513 0.21001712 0.16777763 0.44878676]
 [0.2315568  0.21902629 0.70086386 0.33159518]
 [0.60531566 0.46730913 0.38086519 0.51220433]]
[[0.2315568  0.21902629 0.70086386 0.33159518]
 [0.07702513 0.21001712 0.16777763 0.44878676]
 [0.60531566 0.46730913 0.38086519 0.51220433]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

Let A be a 2D array.
Use (~A.any(axis=0)).any().


In [38]:
A = np.random.rand(2,8)
print(A)
print((~A.any(axis=0)).any())

[[0.97523097 0.17536446 0.84118089 0.72556214 0.49513077 0.19854043
  0.37191749 0.71977176]
 [0.37332544 0.87871635 0.3230713  0.38277387 0.2915114  0.44489549
  0.26107663 0.16812208]]
False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [44]:
a = np.arange(1, 6)
print(a)
b = 3
c = np.zeros(len(a) + b * (len(a) - 1))
c[:: (b+1)] = a
print(c)

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

Let A be an array.  
If you want to swap the i-th and j-th rows, use A[[i, j]] = A[[j, i]].


In [46]:
A = np.identity(5)
print(A)
A[[0, 4]] = A[[4, 0]]
print(A)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

Use np.logical_not() for the boolean version and np.negative for the float.
Let A be a float array.
np.negative(A, out = A)
print(A)

In [47]:
A = np.random.randn(3, 3)
print(A)
np.negative(A, out = A)
print(A)

[[-1.66759998  1.13749506  0.27016004]
 [-0.08544027  0.89322866 -1.92948128]
 [-0.01208837 -0.04382378 -0.17520518]]
[[ 1.66759998 -1.13749506 -0.27016004]
 [ 0.08544027 -0.89322866  1.92948128]
 [ 0.01208837  0.04382378  0.17520518]]


#### 83. How to find the most frequent value in an array?

Let A be a an array.
Then use np.bincount(A).argmax().

In [56]:
A = np.random.randint(0, 4, 8)
print(A)
print(np.bincount(A).argmax())

[2 2 0 3 1 1 0 0]
0


#### 89. How to get the n largest values of an array (★★★)

Let A be an array.
b = np.sort(A, axis = None)
c = b[-n:]
print(c)

In [57]:
A = np.random.randn(5, 5)
n = 3
print(A)
b = np.sort(A, axis = None)
c = b[-n:]
print(c)

[[ 0.2456826  -0.43204118  1.17231589  1.36726464 -0.99815812]
 [-0.14604587 -0.75796723 -1.62954732 -0.1005056  -2.06828635]
 [-1.55465482  0.01059242  0.50815685 -0.98729126  0.69081836]
 [-1.17702225  2.10401132 -0.92839055  0.206092   -0.5244922 ]
 [ 0.24285536  3.22351309  0.69952859  0.25858357  2.35811926]]
[2.10401132 2.35811926 3.22351309]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

Let A be an array.
Then use np.unique(A, axis = 0).

In [62]:
A = np.zeros((5, 5))
np.unique(A, axis = 0)

array([[0., 0., 0., 0., 0.]])